---
- name: Openstack
  hosts: controller[0]
  become: true
  become_user: root
  vars:
    - DB_ROOT_PASS: Password1
  roles:
#    - mariadb
#    - memcaches
#    - rabbitmq
#    - etcd
#    - keystone
#    - glance
#    - placement
#    - nova-controller
#    - neutron-controller
    - cinder-controller