---
- name: Openstack
  hosts: controller[0]
  become: true
  become_user: root
  vars:
#DNS
    - MARIADB_DNS: controller01
    - KEYSTONE_DNS: controller01
    - GLANCE_DNS: controller01
    - PLACEMENT_DNS: controller01
    - NOVA_DNS: controller01
#Mariadb
    - DB_ROOT_PASS: Password1
    - DB_USER: rasmus
    - DB_USER_PASS: Password1!
#Rabbitmq
    - RABBITMQ_PASS: RABBIT_PASS
#Keystone
    - KEYSTONE_DB_PASS: KEYSTONE_DBPASS
    - ADMIN_PASS: ADMIN_PASS
    - REGION: RegionOne
    - DOMAIN: TestCompany
    - DOMAIN_DESCRIPTION: TestCompany domain 
    - PROJECT_DESCRIPTION: production project
    - PROJECT_NAME: production
    - USER_PASS: Password1
    - USERNAME: Test
#Etcd
    - ETCD_TOKEN: new-cluster
#Glance
    - GLANCE_DB_PASS: GLANCE_DBPASS
    - GLANCE_USER_PASS: GLANCE_PASS
    - GLANCE_USER_READ_PASS: GLANCE_READ_PASS
#Nova
    - NOVA_DB_PASS: NOVA_DBPASS
    - NOVA_PASS: NOVA_PASS
    # qemu or kvm
    - VIRT_TYPE: qemu 
#Placement
    - PLACEMENT_DB_PASS: PLACEMENT_DBPASS
    - PLACEMENT_PASS: PLACEMENT_PASS
#Neutron
    - NEUTRON_DB_PASS: NEUTRON_DBPASS
    - NEUTRON_PASS: NEUTRON_PASS
    - METADATA_SECRET: METADATA_SECRET
#Cinder
    - CINDER_DB_PASS: CINDER_DB_PASS
  roles:
#    - mariadb
#    - memcaches
#    - rabbitmq
#    - etcd
    - keystone
    - glance
    - placement
    - nova-controller
#    - neutron-controller
#    - cinder-controller