---
- name: Install commem packet
  ansible.builtin.package:
    name: 
      - memcached
      - python3-memcache
    state: present

- name: Memcached template 
  template:
    src: ./templates/memcached.conf
    dest: /etc/memcached.conf

- name: Start memcached
  ansible.builtin.service:
    name: memcached
    state: started

- name: Enable memcached
  ansible.builtin.service:
    name: memcached
    enabled: yes