---
- name: Install commem packet
  ansible.builtin.package:
    name: 
      - memcached
      - python3-memcache
    state: present

- name: Add memcaches ip to memcached.conf
  template:
    src: ./templates/memcached.conf
    dest: /etc/memcached.conf

- name: Start memcaches
  ansible.builtin.service:
    name: memcached
    state: started

- name: Enable memcaches
  ansible.builtin.service:
    name: memcached
    enabled: yes