---
- name: Install commem packet
  ansible.builtin.package:
    name: 
      - curl
      - gnupg
      - apt-transport-https
    state: present

- name: Install Rabbitmq
  ansible.builtin.shell: | 
    curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg
    curl -1sLf "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg
    curl -1sLf "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/io.packagecloud.rabbitmq.gpg

- name: Creating a file with content
  copy:
    dest: "/etc/apt/sources.list.d/rabbitmq.list"
    content: |
      deb [signed-by=/usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu jammy main
      deb-src [signed-by=/usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu jammy main
      deb [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ jammy main
      deb-src [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ jammy main

- name: Update repo
  ansible.builtin.apt:
    update_cache: yes

- name: Install commem packet
  ansible.builtin.package:
    name: 
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia 
      - erlang-os-mon 
      - erlang-parsetools 
      - erlang-public-key
      - erlang-runtime-tools 
      - erlang-snmp 
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp 
      - erlang-tools 
      - erlang-xmerl
    state: present

- name: Install rebbitmq-server
  ansible.builtin.command: sudo apt-get install rabbitmq-server -y --fix-missing

- name: Start Rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started

- name: Enable Rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: yes

- name: Add user to rabbitmq
  ansible.builtin.shell: rabbitmqctl add_user openstack {{ RABBIT_PASS }}

- name: Add promesion to openstack user
  ansible.builtin.shell: rabbitmqctl set_permissions openstack ".*" ".*" ".*"

- name: Display resolv.conf contents
  command: cat /var/lib/rabbitmq/.erlang.cookie
  register: command_output

- name: Print to console
  debug:
    msg: "{{ command_output.stdout }}"