---
- name: Install lvm2
  ansible.builtin.apt:
    name: lvm2
    state: present

- name: Install thin-provisioning-tools
  ansible.builtin.apt:
    name: thin-provisioning-tools
    state: present

- name: Install cinder-volume
  ansible.builtin.apt:
    name: cinder-volume
    state: present

- name: Install tgt
  ansible.builtin.apt:
    name: tgt
    state: present

- name: Update hosts file
  lineinfile:
    path: /etc/hosts
    line: |
      192.168.56.7 controller01
      192.168.56.8 compute01

- name: Create the LVM physical volume
  command: pvcreate /dev/sdb

- name: Create the LVM volume group cinder-volumes
  command: vgcreate cinder-volumes /dev/sdb

- name: 
  lineinfile:
    path: "/etc/lvm/lvm.conf"
    insertafter: '^\s*devices {\s*$'
    line: '      filter = [ "a/sda/", "a/sdb/", "r/.*/"]'

- name: Config nova-compute
  ansible.builtin.template:
    src: ./templates/cinder.conf
    dest: /etc/cinder/cinder.conf
    owner: root
    group: cinder
    mode: '0644'

- name: Restart tgt
  ansible.builtin.service:
    name: tgt
    state: restarted

- name: Restart cinder-volume
  ansible.builtin.service:
    name: cinder-volume
    state: restarted