---
- name: Update repo
  ansible.builtin.apt:
    update_cache: yes

- name: Install recomendet packet
  apt:
    name:
      - mariadb-server 
      - python3-pymysql
    state: present

- name: Config mariadb
  template:
    src: ./templates/99-openstack.cnf
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf

- name: test mysql_secure_installation
  mysql_secure_installation:
    login_password: ''
    new_password: {{ DB_ROOT_PASS }}
    user: root
    login_host: localhost
    hosts: ['localhost', '127.0.0.1', '::1']
    change_root_password: true
    remove_anonymous_user: true
    disallow_root_login_remotely: true
    remove_test_db: true
  register: mysql_secure

- debug:
    var: mysql_secure

- name: Create DB user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ login_password }}"
    state: present
    name: rasmus
    password: "{{ password }}"
    priv: '*.*:ALL,GRANT'
    tls_requires:
      x509:

- name: Create keystone DB
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ login_password }}"
    name: keystone
    state: present

- name: Create keystone user 
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ login_password }}"
    state: present
    name: keystone
    password: "{{ keystone_pass_db }}"
    priv:
      'keystone.*': 'ALL,GRANT'

- name: Create glance DB
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ login_password }}"
    name: glance
    state: present

- name: Create glance user 
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ login_password }}"
    state: present
    name: glance
    password: "{{ glance_pass_db }}"
    priv:
      'glance.*': 'ALL,GRANT'

- name: Create nova DB
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ login_password }}"
    name: 
      - nova_api
      - nova
      - nova_cell0
    state: present


- name: Create nova user 
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ login_password }}"
    state: present
    name: nova
    password: "{{ nova_dbpass }}"
    priv:
      'nova_api.*': 'ALL,GRANT'
      'nova.*': 'ALL,GRANT'
      'nova_cell0.*': 'ALL,GRANT'

- name: Create placement DB
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ login_password }}"
    name: placement
    state: present

- name: Create placement user 
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ login_password }}"
    state: present
    name: placement
    password: "{{ placement_pass_db }}"
    priv:
      'placement.*': 'ALL,GRANT'

- name: Create neutron DB
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ login_password }}"
    name: neutron
    state: present

- name: Create neutron user 
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ login_password }}"
    state: present
    name: neutron
    password: "{{ neutron_dbpass }}"
    priv:
      'neutron.*': 'ALL,GRANT'

- name: Create cinder DB
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ login_password }}"
    name: cinder
    state: present

- name: Create cinder user 
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ login_password }}"
    state: present
    name: cinder
    password: "{{ cinder_dbpass }}"
    priv:
      'cinder.*': 'ALL,GRANT'

- name: Restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: Enable mariadb
  ansible.builtin.service:
    name: mariadb
    enabled: yes