---
- name: Install nova pacektes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-linuxbridge-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: Config neutron
  ansible.builtin.template:
    src: ./templates/neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: '0644'

- name: Config ml2_conf
  ansible.builtin.template:
    src: ./templates/ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: '0644'

- name: Enable br_netfilter
  shell: "{{ item }}"
  with_items:
    - modprobe br_netfilter
    - sh -c 'echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf'

- name: Config linuxbridge_agent
  ansible.builtin.template:
    src: ./templates/linuxbridge_agent.ini
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: neutron
    mode: '0644'

- name: Config l3_agent
  ansible.builtin.template:
    src: ./templates/l3_agent.ini
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: neutron
    mode: '0644'

- name: Config dhcp_agent
  ansible.builtin.template:
    src: ./templates/dhcp_agent.ini
    dest: /etc/neutron/dhcp_agent.ini
    owner: root
    group: neutron
    mode: '0644'

- name: Config metadata_agent
  ansible.builtin.template:
    src: ./templates/metadata_agent.ini
    dest: /etc/neutron/metadata_agent.ini
    owner: root
    group: neutron
    mode: '0644'

- name: Populate the database
  command: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

- name: Include neutron-compute role
  include_role:
    name: neutron-compute
    apply:
      delegate_to: "{{ item }}"
  with_items: "{{ groups['compute'] }}"

- name: Restart nova services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nova-api
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent