---
- name: Install commem packet
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: Add openstack user 
  command: rabbitmqctl add_user openstack {{ RABBITMQ_PASS }}

- name: Giv openstack user permissions
  command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"

- name: Start memcaches
  ansible.builtin.service:
    name: rabbitmq-server
    state: started

- name: Enable memcaches
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: yes