---
- name: Install commem packet
  ansible.builtin.package:
    name: 
      - memcached
      - python3-memcache
#      - build-essential
#      - wget
#      - libevent-dev
    state: present

#- name: Download memcached
#  ansible.builtin.get_url:
#    url: "{{ memcaches_url }}"
#    dest: "{{ memcaches_tar }}"

#- name: Extract memcached
#  ansible.builtin.unarchive:
#    src: "{{ memcaches_tar }}"
#    dest: /tmp/
#    remote_src: yes

#- name: Run configure
#  command: chdir="{{ memcaches_location }}" ./configure

#- name: Run make
#  command: chdir="{{ memcaches_location }}" make

#- name: Run make test
#  command: chdir="{{ memcaches_location }}" make test

#- name: Run make install
#  command: chdir="{{ memcaches_location }}" sudo make install


#- name: Build the default target
#  make:
#    chdir: "{{ memcaches_location }}"

#- name: Install 
#  shell:  "{{ item }}" #./configure && make && make test && sudo make install
#  args:
#    chdir: "{{ memcaches_location }}"
#  with_items:
#    - cd /tmp/memcaches-1.6.17
#    - ./configure
#    - make
#    - make test
#    - sudo make install


#./configure && make && make test && sudo make install

#- name: Install Rabbitmq
#  ansible.builtin.script: ./files/install_rabbitmq.sh

- name: Add memcaches ip to memcached.conf
  ansible.builtin.lineinfile:
    path:  /etc/memcached.conf
    regexp: '^-l 127.0.0.1'
    line: -l {{ controller0 }}

- name: Start memcaches
  ansible.builtin.service:
    name: memcached
    state: started

- name: Enable memcaches
  ansible.builtin.service:
    name: memcached
    enabled: yes